Controllers/RcpgController.cs
using Grpc.Core;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Rcpg;
using RcpgMicroserviceClient.Entities;
using RcpgMicroserviceClient.Models;
using RcpgMicroserviceClient.Services;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

using static RcpgMicroserviceClient.Models.ErrorType;
using static System.String;


namespace RcpgMicroserviceClient.Controllers
{
    public class RcpgController : Controller
    {
        private readonly Channel channel;
        private readonly IRcpgClient rcpgClient;
        private readonly IPaymentRepository paymentRepository;
        private const string DEFAULT_CURRENCY = "EUR";
        private const string CONFIRM_RETURN_URL = "http://127.0.0.1:5000/Rcpg/PayCardless";
        private const string CANCELED_RETURN_URL = "http://127.0.0.1:5000/Rcpg/CanceledReturn";

        public RcpgController(Channel channel, IRcpgClient rcpgClient, IPaymentRepository paymentRepository)
        {
            this.channel = channel;
            this.rcpgClient = rcpgClient;
            this.paymentRepository = paymentRepository;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult NewPayment()
        {
            return View();
        }

        public async Task<IActionResult> CanceledReturn([FromQuery] string token)
        {
            TempData["actionInitiated"] = true;

            if (string.IsNullOrEmpty(token))
            {
                setError(EmptyReturnParam);
                return redirectToLandingPage();
            }

            var payment = await paymentRepository.Track(token);
            if (payment == null)
            {
                setError(PaymentNotFound);
                return redirectToLandingPage();
            }

            // Can only cancel a payment that has been initiated.
            if (Enum.Parse<PaymentStatus>(payment.Status) != PaymentStatus.Initiated)
            {
                setError(NotCancelable);
                return redirectToLandingPage();
            }

            payment.Status = PaymentStatus.Canceled.ToString();
            await paymentRepository.Update(payment);

            TempData["notificationText"] = $"Maksājums ar marķieri: \"{token}\" ir atcelts";
            return redirectToAllPayments();
        }

        public async Task<IActionResult> PayCardless([FromQuery] string token, [FromQuery] string PayerID)
        {
            TempData["actionInitiated"] = true;

            if (string.IsNullOrEmpty(token) || string.IsNullOrEmpty(PayerID))
            {
                setError(EmptyReturnParam);
                return redirectToLandingPage();
            }

            var payment = await paymentRepository.Track(token);
            if (payment == null)
            {
                setError(PaymentNotFound);
                return redirectToLandingPage();
            }
            PayResponse response = await rcpgClient.PayCardless(PayerID, payment);

            if (response.PaymentErrors.Any())
            {
                TempData["hasErrors"] = true;
                TempData["notificationText"] = $"Notikusi kļūda. Kļūdas avots: \"{response.PaymentErrors.First().Source}\", kļūdas kods: \"{response.PaymentErrors.First().ErrorCode}\"";
                return redirectToLandingPage();
            }

            if (Enum.Parse<Intent>(payment.Intent) == Intent.Purchase)
            {
                payment.Status = PaymentStatus.Captured.ToString();
                payment.CapturedOn = DateTime.Parse(response.ExecutedOn);
            }
            else
            {
                payment.Status = PaymentStatus.Authorized.ToString();   
            }
            payment.TransactionId = response.PaymentId;

            await paymentRepository.Update(payment);

            TempData["notificationText"] = $"Veiksmīgs maksājums ar transakcijas identifikatoru: \"{response.PaymentId}\"";
            return redirectToAllPayments();
        }

        [HttpPost]
        public async Task<IActionResult> PayStandard(Provider provider, int paymentSum, PaymentCard paymentCard, Intent intent)
        {
            TempData["actionInitiated"] = true;
            if (intent == Intent.NoIntent)
            {
                setError(InvalidIntent);
                return redirectToLandingPage();
            }

            // Let's assume payment sum and payment card gets validated on the client side, so no need to do it here.

            PayResponse response = await rcpgClient.PayStandard(provider, paymentSum, DEFAULT_CURRENCY, paymentCard, intent);

            if (response.PaymentErrors.Any())
            {
                TempData["hasErrors"] = true;
                TempData["notificationText"] = $"Notikusi kļūda. Kļūdas avots: \"{response.PaymentErrors.First().Source}\", kļūdas kods: \"{response.PaymentErrors.First().ErrorCode}\"";
                return redirectToLandingPage();
            }

            Payment payment = new Payment()
            {
                Token = response.PaymentId,
                Sum = paymentSum,
                Currency = DEFAULT_CURRENCY,
                Provider = provider.ToString(),
                Intent = intent.ToString(),
                TransactionId = response.PaymentId,
                InitiatedOn = DateTime.Parse(response.ExecutedOn)
            };
            if (intent == Intent.Purchase)
            {
                payment.Status = PaymentStatus.Captured.ToString();
                payment.CapturedOn = DateTime.Parse(response.ExecutedOn);
            }
            else
            {
                payment.Status = PaymentStatus.Authorized.ToString();
            }
            await paymentRepository.Add(payment);

            return redirectToAllPayments();
        }

        [HttpPost]
        public async Task<IActionResult> CapturePayment(string transactionId)
        {
            TempData["actionInitiated"] = true;
            if (string.IsNullOrEmpty(transactionId))
            {
                setError(EmptyTransactionId);
                return redirectToLandingPage();
            }

            var payment = await paymentRepository.TrackByTransactionId(transactionId);
            if (payment == null)
            {
                setError(PaymentNotFound);
                return redirectToLandingPage();
            }

            PayResponse response = await rcpgClient.Capture(payment);

            if (response.PaymentErrors.Any())
            {
                TempData["notificationText"] = $"Notikusi kļūda. Kļūdas avots: \"{response.PaymentErrors.First().Source}\", kļūdas kods: \"{response.PaymentErrors.First().ErrorCode}\"";
                return redirectToLandingPage();
            }

            payment.Status = PaymentStatus.Captured.ToString();
            payment.TransactionId = response.PaymentId;
            payment.CapturedOn = DateTime.Parse(response.ExecutedOn);
            
            await paymentRepository.Update(payment);

            TempData["notificationText"] = $"Veiksmīga nokārtošana ar identifikatoru: \"{response.PaymentId}\"";
            return redirectToAllPayments();
        }

        public async Task<IActionResult> AllPayments()
        {
            return View(await paymentRepository.GetAll());
        }

        public async Task<IActionResult> Details(string id)
        {
            TempData["actionInitiated"] = true;

            var payment = await paymentRepository.Find(id);
            var provider = Enum.Parse<Provider>(payment.Provider);
            var identifier = payment.TransactionId ?? payment.Token;
            PaymentIdType idType = payment.TransactionId == null ? PaymentIdType.Token : PaymentIdType.TransactionId;
            
            GetDetailsResponse response = await rcpgClient.GetDetails(provider, identifier, idType);

            if (response.Errors.Any())
            {
                TempData["hasErrors"] = true;
                TempData["notificationText"] = $"Notikusi kļūda. Kļūdas avots: \"{response.Errors.First().Source}\", kļūdas kods: \"{response.Errors.First().ErrorCode}\"";
                return redirectToLandingPage();
            }

            string json = JObject.Parse(response.Details).ToString(Formatting.Indented);
            return View("Details", json);
        }

        [HttpPost]
        public async Task<IActionResult> InitiateCardless(Provider provider, int paymentSum, Intent intent)
        {
            TempData["actionInitiated"] = true;
            if (intent == Intent.NoIntent)
            {
                setError(InvalidIntent);
                return redirectToLandingPage();
            }

            InitiateCardlessResponse response = await rcpgClient.InitiateCardless(provider, intent, paymentSum, DEFAULT_CURRENCY, CONFIRM_RETURN_URL, CANCELED_RETURN_URL);

            if (response.PaymentErrors.Any())
            {
                TempData["hasErrors"] = true;
                TempData["notificationText"] = $"Notikusi kļūda. Kļūdas avots: \"{response.PaymentErrors.First().Source}\", kļūdas kods: \"{response.PaymentErrors.First().ErrorCode}\"";
                return redirectToLandingPage();
            }

            Payment payment = new Payment()
            {
                Token = response.Token,
                Sum = paymentSum,
                Currency = DEFAULT_CURRENCY,
                Provider = provider.ToString(),
                Intent = intent.ToString(),
                Status = PaymentStatus.Initiated.ToString(),
                InitiatedOn = DateTime.Parse(response.InitiatedOn)
            };

Views/Rcpg/AllPayments.cshtml
@model List<RcpgMicroserviceClient.Entities.Payment>
@{
    ViewData["Title"] = "Visi maksājumi";
}


@{ 
    if ((bool?)TempData["actionInitiated"] == true )
    {
        string notificationType = ((bool?)TempData["hasErrors"] ?? false) ? "danger" : "success";
        string notificationText = (string)TempData["notificationText"];
        <div class="alert alert-@notificationType">
            @notificationText
        </div>
    }
}

<h2>Visi maksājumi</h2>

<table class="table">
    <thead>
        <tr>
                <th>
                    Marķieris
                </th>
                <th>
                    Summa
                </th>
                <th>
                    Valūta
                </th>
                <th>
                    Starpnieks
                </th>
                <th>
                    Nolūks
                </th>
                <th>
                    Statuss
                </th>
                <th>
                    TransakcijasId
                </th>
                <th>
                    Iniciēts
                </th>
                <th>
                    Nokārtots
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var payment in Model) {
    bool isCapturable = 
        Enum.Parse<Rcpg.Intent>(payment.Intent) == Rcpg.Intent.Authorization && 
        Enum.Parse<RcpgMicroserviceClient.Models.PaymentStatus>(payment.Status) == RcpgMicroserviceClient.Models.PaymentStatus.Authorized;

    // string idAndParams = (payment.TransactionId != null) ? payment.TransactionId + "?isTransaction=true" : payment.Token;

        <tr>
            <td>
                <a href="/Rcpg/Details/@payment.Token" title="Iegūt pilnu informāciju">
                    @Html.DisplayFor(modelItem => payment.Token)
                </a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => payment.Sum)
            </td>
            <td>
                @Html.DisplayFor(modelItem => payment.Currency)
            </td>
            <td>
                @Html.DisplayFor(modelItem => payment.Provider)
            </td>
            <td>
                @Html.DisplayFor(modelItem => payment.Intent)
            </td>
            <td>
                @if (isCapturable) {
                    <form asp-controller="Rcpg" asp-action="CapturePayment" method="post">
                        <button type="submit" class="button-as-anchor" name="transactionId" value="@payment.TransactionId" title="Nokārtot autorizētu maksājumu">@payment.Status</button>
                    </form>
                }
                else {
                    @Html.DisplayFor(modelItem => payment.Status)
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => payment.TransactionId)
            </td>
            <td>
                @payment.InitiatedOn.ToString("dd.MM.yyyy. HH:mm:ss")
            </td>
            <td>
                @(payment.CapturedOn.HasValue ? ((DateTime)payment.CapturedOn).ToString("dd.MM.yyyy. HH:mm:ss") : "")
            </td>
        </tr>
}
    </tbody>
</table>

Views/Rcpg/Details.cshtml
@model System.String

<h3>
    Raw payment details:
</h3>
<pre style="font-size:15px;">
    @Model
</pre>

Views/Rcpg/Index.cshtml
@{
    ViewData["Title"] = "Mērķlapa";
}

@{ 
    if ((bool?)TempData["actionInitiated"] == true )
    {
        string notificationType = ((bool?)TempData["hasErrors"] ?? false) ? "danger" : "success";
        string notificationText = (string)TempData["notificationText"];
        <div class="alert alert-@notificationType">
            @notificationText
        </div>
    }
}

<h3>@ViewData["Title"]</h3>

<p>
    Izmantojiet izvēlnes joslu, lai pārvietotos uz jauna maksājuma skatu, visu maksājumu skatu un asinhronās ziņojumapmaiņas patērētāja skatu.
</p>

<p>
    Nospiediet pogu, lai slēgtu gRPC kanālu. Brīdinājums: gRPC kanālu no jauna pieslēgt varēs tikai pēc klienta restarta.
</p>

<form asp-action="ShutdownChannel" method="POST">
    <input type="submit" value="Slēgt gRPC kanālu">
</form>

Views/Rcpg/NewPayment.cshtml
@{
    ViewData["Title"] = "Veikt maksājumu";
}

<h3 style="text-align:center;">@ViewData["Title"]</h3>
<div style="width:100%;margin:40px 0 40px 0;">
    <form asp-controller="Rcpg" asp-action="InitiateCardless" method="post" style="margin:auto;width:50%;">
        <h4 style="text-align:center;">Izmantojot PayPal Express Gateway</h4>
        <input type="text" name="paymentSum" placeholder="Summa" style="width:100%;margin:0 0 10px 0;"/>
        <input type="hidden" name="provider" value="@Rcpg.Provider.PaypalExpressGateway" />

        <button type="submit" class="like" name="intent" value="Purchase">Maksāt tagad</button>
        <button type="submit" class="like" name="intent" value="Authorization">Maksāt, kad produkts būs pieejams</button>
    </form>
</div>

<div style="width:100%;margin:40px 0 40px 0;">
    <form asp-controller="Rcpg" asp-action="PayStandard" method="post" style="margin:auto;width:50%;">
        <h4 style="text-align:center;">Izmantojot Authorize.NET</h4>
        <input type="text" name="paymentSum" placeholder="Summa" style="width:100%;margin:0 0 10px 0;"/>
        
        <!-- Payment Card -->
        <input type="text" name="PrimaryNumber" placeholder="Kartes numurs" style="width:100%;margin:0 0 10px 0;"/>
        <input type="text" name="FirstName" placeholder="Vārds" style="width:100%;margin:0 0 10px 0;"/>
        <input type="text" name="LastName" placeholder="Uzvārds" style="width:100%;margin:0 0 10px 0;"/>
        <input type="text" name="Month" placeholder="Mēnesis" style="width:45%;margin:0 0 10px 0;"/>
        <input type="text" name="Year" placeholder="Gads" style="width:45%;margin:0 0 10px 0;"/>
        <input type="text" name="VerificationValue" placeholder="Drošības kods" style="width:100%;margin:0 0 10px 0;"/>
        <!-- Payment Card -->

        <input type="hidden" name="provider" value="@Rcpg.Provider.AuthorizeNetGateway" />

        <button type="submit" class="like" name="intent" value="Purchase">Maksāt tagad</button>
        <button type="submit" class="like" name="intent" value="Authorization">Maksāt, kad produkts būs pieejams</button>
    </form>
</div>